### ISSUE TITLE
White space 

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#10]
There seems to be a lot of white space, can we please try and reduce this. 

This is what we see - 
<img width="1238" alt="Screen Shot 2019-10-14 at 10 26 32 am" src="https://user-images.githubusercontent.com/55725505/66724088-1acd0300-ee6d-11e9-9ded-7ceeb79d1aa7.png">

This is what Paul sent over

<img width="761" alt="Screen Shot 2019-10-14 at 10 23 25 am" src="https://user-images.githubusercontent.com/55725505/66724099-26202e80-ee6d-11e9-9fe9-17a815cf4190.png">

**Comment by markendley** [comment]
I reduced the spacing in between paragraphs

or does Paul really want it that tight?

**Comment by LaraStudioFriday** [comment]
There still seems to be a lot of white space generally - this is on a phone

![72921776_458261318148498_4249227367471382528_n](https://user-images.githubusercontent.com/55725505/66726245-ec0e5700-ee83-11e9-92b9-5ef64e40c3a4.jpg)

**Comment by LaraStudioFriday** [comment]
![72211371_399507340742062_9193886734180417536_n](https://user-images.githubusercontent.com/55725505/66726969-09452480-ee88-11e9-94f2-b1f228c44619.jpg)

**Comment by markendley** [comment]
fixed
