### ISSUE TITLE
Full width gallery

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#11]
How do i do this? These 3 should be in a full width gallery (http://marke2.sg-host.com/plumpspry/case-study/qvb-lunar-new-year/)

<img width="1227" alt="Screen Shot 2019-10-14 at 11 07 29 am" src="https://user-images.githubusercontent.com/55725505/66724546-e78d7280-ee72-11e9-8ac2-f17dfa5e1d33.png">

**Comment by markendley** [comment]
added a new radio button

![Screen Shot 2019-10-14 at 11 30 08 am](https://user-images.githubusercontent.com/6570606/66724845-810a5380-ee76-11e9-9a20-7011b0eff32f.png)
