### ISSUE TITLE
Question about loop videos

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#12]
on this page - http://marke2.sg-host.com/plumpspry/case-study/pacificepping/

There are 3 videos on loop. 

Looking at the image I sent you on chat - and here, do you think Paul would like these as smaller boxes, not placed one above the other but in a row (on a laptop) I assume on a phone they would have be one above the other - or would you put this as a slider? 

Do they have to have the video bar at the bottom? Is there a way they could play as gifs? 

I really dont know what options we have - so if you can recommend what to do I can go back to Paul with options and costs? 
<img width="751" alt="Screen Shot 2019-10-14 at 12 03 30 pm" src="https://user-images.githubusercontent.com/55725505/66725284-178d4380-ee7c-11e9-9cef-ee7f24967db1.png">

Also on a phone they are taking a while to load  - what is the best file size for these?

**Comment by markendley** [comment]
I think we already spoke about all this over chat?

I created a new field where you can add more than one video in a gallery
and then set each one as loop or no loop

- when it is on loop it'll autoplay and without audio
- when it is NOT on loop, it'll show the controls (hence the video bar at the bottom)

http://marke2.sg-host.com/plumpspry/case-study/videos/
