### ISSUE TITLE
Homepage image

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#15]
Is there a way to zoom out of this pic so the girl doesn't appear really large?
<img width="685" alt="Screen Shot 2019-11-05 at 1 36 18 pm" src="https://user-images.githubusercontent.com/55725505/68174200-5329b200-ffd1-11e9-9f96-f0d85ff546ac.png">

**Comment by markendley** [comment]
Just upload another image

Once where the girl is zoomed back

**Comment by LaraStudioFriday** [comment]
?? There is only 1 image of her - http://marke2.sg-host.com/plumpspry/wp-admin/upload.php?item=593

**Comment by markendley** [comment]
yes the one you've uploaded is too zoomed in so upload a new image with her zoomed out
