### ISSUE TITLE
Loop videos

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#17]
From Paul - When we want video to loop, can we remove the rollover in that instance? It looks bad… ie.
![image013](https://user-images.githubusercontent.com/55725505/68175470-735b7000-ffd5-11e9-9fcc-6db281319b42.png)

**Comment by markendley** [comment]
done

**Comment by LaraStudioFriday** [comment]
It is still there
<img width="1266" alt="Screen Shot 2019-11-18 at 3 22 59 pm" src="https://user-images.githubusercontent.com/55725505/69024555-5a13e400-0a17-11ea-9287-011580602c62.png">

**Comment by markendley** [comment]
awaiting Paul's decision if we're sticking with these or switching to Vimeo

**Comment by markendley** [comment]
Now they are all vimeo!

For now on, when you add videos 
- you have to upload a place holder image
- stick in the Vimeo code
- You now have the option of "Loop"
- You now have the option of "Autoplay" - but autoplay won't work on some mobile devices
- Ignore the first column, you are now longer uploading mp4s, this column will disapear after you've added in all the Vimeos

![Screen Shot 2019-11-19 at 9 10 27 pm](https://user-images.githubusercontent.com/6570606/69137543-156c7380-0b11-11ea-96af-72776bdb00c6.png)

**Comment by markendley** [comment]
When you're done, lemme know and I'll clear out the mp4 columns.
