### ISSUE TITLE
3 video on loop for pacific epping - http://marke2.sg-host.com/plumpspry/case-study/pacificepping/

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#18]
Paul has said - 3 videos in a row would be better (on a desktop).

Would prefer not to use Animated gifs as these tend to affect the image quality. As above, Please also get rid of rollovers.

**Comment by markendley** [comment]
Ready

For now on you'll see a set of fields where you can choose how many videos you wanna display in that section

1 in a row
2 in a row
3 in a row

http://marke2.sg-host.com/plumpspry/case-study/videos/
