### ISSUE TITLE
Add full width gallery function to a case study page

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#2]
E.G on this page http://marke2.sg-host.com/plumpspry/case-study/qvb-lunar-new-year/

Where there is the one full width image - can this be where the full width gallery sits.

On a phone he would like the swipe functionality - see image of calvin klein.

I realise that Paul is asking for extra functionality - so please feel free to estimate any extra costs for this project. 
<img width="785" alt="Screen Shot 2019-09-26 at 1 35 11 pm" src="https://user-images.githubusercontent.com/55725505/65656242-7f612300-e062-11e9-9daf-04a04650c9d1.png">
<img width="848" alt="Screen Shot 2019-09-26 at 1 51 23 pm" src="https://user-images.githubusercontent.com/55725505/65656972-031c0f00-e065-11e9-9a16-e79045f9bf87.png">

<img width="347" alt="image001 (2)" src="https://user-images.githubusercontent.com/55725505/65734402-1e932280-e116-11e9-844f-c76dcf2298d0.png">

**Comment by markendley** [comment]
done, though the pagination buttons have to appear on tablet as well as mobile

**Comment by LaraStudioFriday** [comment]
As per our chat this morning - these need to be full width images and fade through, thanks

**Comment by markendley** [comment]
done.

Upload images at least 2000px wide.

If you don't like it when the slider adjusts height, make sure the images are at least 750px tall.

**Comment by LaraStudioFriday** [comment]
Can you please force this 750px tall? This is going to be difficult for Paul to update if he needs to upload images at a certain size  - just need it to be easy for him.

**Comment by markendley** [comment]
Force it to be 750px tall?

I want this to be easy for him too, but if I do could implicate really blurry images. 

If Paul doesn't have images that are 2000 by 750 px (or bigger), he shouldn't put them all full width gallery slider.

What size images does Paul have?

**Comment by LaraStudioFriday** [comment]
His images are pretty huge so i dont think blurry images will be an issue, thanks
