### ISSUE TITLE
Please add 3 videos in a row

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#20]
<img width="199" alt="Screen Shot 2019-11-08 at 2 09 56 pm" src="https://user-images.githubusercontent.com/55725505/68446901-30e29f00-0232-11ea-8a6d-06421010520f.png">

so i can add the animations for Paul

**Comment by LaraStudioFriday** [comment]
As per chat - we might onyl show 2 videos in a row - but can we still see the option of three - but not on auto play

**Comment by markendley** [comment]
I created a new set of fields called "Video gallery"

See demo
http://marke2.sg-host.com/plumpspry/case-study/videos/
