### ISSUE TITLE
About us page

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#22]
Paul has 5 lists of services, and currently we have 4 columns. 

What do you suggest we can do? It's fine on a phone - but on a laptop, maybe 3 list on 1 line and 2 on the second line (all centred) 

<img width="1263" alt="Screen Shot 2019-11-11 at 2 07 02 pm" src="https://user-images.githubusercontent.com/55725505/68560075-8b2e6a80-0493-11ea-9177-c0232f95c5a8.png">

Pauls content sent to me..
<img width="625" alt="Screen Shot 2019-11-11 at 2 08 45 pm" src="https://user-images.githubusercontent.com/55725505/68560099-a4cfb200-0493-11ea-8db2-d9f48747a2a0.png">

**Comment by markendley** [comment]
I'll to 5 columns in a row
then 3 2 on tablet
2 on smaller tablet
then 1 on mobile
