### ISSUE TITLE
WP Rocket

### ISSUE THREAD

**Issue by markendley** [markendley/plmpndspry#27]
Hey Lara,

To add full optimization to the images,
Paul should get this plugin
https://wp-rocket.me/

What it does it reduces the size of the images WITHOUT reducing it's quality/resolution.

**Comment by LaraStudioFriday** [comment]
ok - paul wants me to purchase this on his behalf

**Comment by LaraStudioFriday** [comment]
ok paul wants me to purchase this on his behalf

**Comment by markendley** [comment]
Lara, lemme activate this plugin after we launch, right now it's heavily caching a bunch of design changes we're making
