### ISSUE TITLE
Connor case study

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#28]
This is still showing a lot of white space
<img width="1271" alt="Screen Shot 2019-11-19 at 10 26 03 am" src="https://user-images.githubusercontent.com/55725505/69102624-0fe23f80-0ab7-11ea-8bc8-7dd78190080e.png">

**Comment by markendley** [comment]
oh, I thought you meant the space after the headings.

OR, for now whenever you add a "Text" you'l see a checkbox called "Space below", so just uncheck it to reduce the space below it.
