### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#29]
Please close up the white space
<img width="1260" alt="Screen Shot 2019-11-19 at 10 52 58 am" src="https://user-images.githubusercontent.com/55725505/69103916-cac00c80-0aba-11ea-9534-ae546b628108.png">
<img width="1264" alt="Screen Shot 2019-11-19 at 10 53 05 am" src="https://user-images.githubusercontent.com/55725505/69103917-cac00c80-0aba-11ea-9295-76e2d7d3e189.png">

**Comment by markendley** [comment]
done
