### ISSUE TITLE
Video to play on loop

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#3]
Can we please add this functionality to the case study pages. E.g on this page - http://marke2.sg-host.com/plumpspry/case-study/qvb-lunar-new-year/

Where the image of the pigs is, can this be a video that plays on loop.
<img width="1246" alt="Screen Shot 2019-09-26 at 1 41 05 pm" src="https://user-images.githubusercontent.com/55725505/65656481-5b521180-e063-11e9-911b-26814343218a.png">
<img width="767" alt="Screen Shot 2019-09-26 at 1 41 47 pm" src="https://user-images.githubusercontent.com/55725505/65656510-6c9b1e00-e063-11e9-9516-aa4a9006b1a7.png">

**Comment by markendley** [comment]
done. for now on, you'll see a checkbox called "loop"

**Comment by LaraStudioFriday** [comment]
I can see two videos posted - but we need just 1 video that will replace the image of the pigs
<img width="835" alt="Screen Shot 2019-10-08 at 4 40 15 pm" src="https://user-images.githubusercontent.com/55725505/66370070-90a71980-e9ea-11e9-92f4-931cb90f2924.png">
<img width="873" alt="Screen Shot 2019-10-08 at 4 40 24 pm" src="https://user-images.githubusercontent.com/55725505/66370072-90a71980-e9ea-11e9-9ed2-8c199c956626.png">
