### ISSUE TITLE
Approach page

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#30]
Why is the hyperlink to the email address not working?
<img width="1266" alt="Screen Shot 2019-11-19 at 10 55 52 am" src="https://user-images.githubusercontent.com/55725505/69104055-32765780-0abb-11ea-9bdd-f60c92a2c7dd.png">
<img width="1206" alt="Screen Shot 2019-11-19 at 10 56 00 am" src="https://user-images.githubusercontent.com/55725505/69104056-330eee00-0abb-11ea-851b-35dcd42bbfc7.png">

**Comment by markendley** [comment]
Usually Wordpress will detect that it's an email address and then put "mailto:" infront of it, I'm not sure why it didn't do it this time, so I just edited the code for ya
