### ISSUE TITLE
Homepage on a phone

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#31]
Can the crop of these images be square like Pauls screen shot.
![image007](https://user-images.githubusercontent.com/55725505/69115051-5ba6e000-0adb-11ea-98fc-9af7bf7d0550.png)
<img width="246" alt="Screen Shot 2019-11-19 at 2 46 58 pm" src="https://user-images.githubusercontent.com/55725505/69115092-7e38f900-0adb-11ea-8787-8fa5c2b8379b.png">

**Comment by markendley** [comment]
done
