### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#35]
On the social media page, the videos aren't showing up?
<img width="1255" alt="Screen Shot 2019-11-21 at 12 18 55 pm" src="https://user-images.githubusercontent.com/55725505/69292059-258f6a80-0c59-11ea-9e66-d8bab9ed5409.png">

**Comment by markendley** [comment]
fixed.

For now on don't use "Video", but use "Video gallery".
