### ISSUE TITLE
Issue with MP4 showing black lines

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#36]
Need options for Paul - he doesnt like the rollovers.

Please let me know extra costs for extra coding.

Need to reduce the size of the video - it plays to the whole screen size.

**Comment by markendley** [comment]
The "rollovers" are the default player controls made by the browser.

To turn it off, he has to set the video on "autoplay" (check the checkbox).

Now, if he wants to upload mp4s that Don't have autoplay I'll need another 30m.
