### ISSUE TITLE
Catalogues has different spacing

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#37]
compared to social media and video - see images.

![77047913_2583193535061157_5515489232203808768_n](https://user-images.githubusercontent.com/55725505/69596087-8b169900-1055-11ea-8350-c9091cfb5717.jpg)
![77057242_1479627042189127_1854982798750777344_n](https://user-images.githubusercontent.com/55725505/69596088-8b169900-1055-11ea-8ebe-bdc04a04a536.jpg)
![78567268_540189003227759_2422411183291105280_n](https://user-images.githubusercontent.com/55725505/69596106-98338800-1055-11ea-9470-957e1c563db8.jpg)

**Comment by markendley** [comment]
the space under the heading?
Fixed.
