### ISSUE TITLE
spacing of grid

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#38]
Paul would like this consistent  - please can the white gaps all be the same size - use the space between the face (canberra) and pacific epping) 
<img width="587" alt="Screen Shot 2019-12-03 at 9 25 42 am" src="https://user-images.githubusercontent.com/55725505/70000362-04127500-15af-11ea-9cd4-92af1198524b.png">

**Comment by markendley** [comment]
Yes I fixed this last week.

**Comment by markendley** [comment]
see
![Screen Shot 2019-12-03 at 5 52 46 pm](https://user-images.githubusercontent.com/6570606/70027219-bec56600-15f5-11ea-894e-6b228d76dbfc.png)
