### ISSUE TITLE
Images getting cropped

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#39]
You can see the images are loaded as a complete image in the media library, but on the front end - they are being cropped?  How can we fix this for Paul?

<img width="877" alt="Screen Shot 2019-12-03 at 9 33 05 am" src="https://user-images.githubusercontent.com/55725505/70000903-0de8a800-15b0-11ea-9291-ba89ad000ab1.png">
<img width="1263" alt="Screen Shot 2019-12-03 at 9 34 18 am" src="https://user-images.githubusercontent.com/55725505/70000918-1b059700-15b0-11ea-9892-49e462d9312d.png">

**Comment by markendley** [comment]
OK, I got an idea

For now on, you'll see a field called "Background Size".

So for those pictures, choose "Contain".

**Comment by markendley** [comment]
tadaa

http://marke2.sg-host.com/plumpspry/case-study/digital-content-robina-town-centre/

**Comment by LaraStudioFriday** [comment]
Confused - no the images have dissappeared??
<img width="1267" alt="Screen Shot 2019-12-04 at 10 13 19 am" src="https://user-images.githubusercontent.com/55725505/70097982-cd0b9480-167e-11ea-8994-95a6d4b589bd.png">

**Comment by markendley** [comment]
Just cleared my cache, they're still there

![Screen Shot 2019-12-04 at 11 03 08 am](https://user-images.githubusercontent.com/6570606/70100395-b0bf2600-1685-11ea-9809-cb3a1b6185f1.png)
