### ISSUE TITLE
3 images in a row functionality to be added to a case study page

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#4]
Where the two images sit, can they actually sit 3 - see images

http://marke2.sg-host.com/plumpspry/case-study/qvb-lunar-new-year/

Add the images in same size as Paul sent through (image of the 3)

Maybe a three and four column please.

<img width="1237" alt="Screen Shot 2019-09-26 at 1 44 05 pm" src="https://user-images.githubusercontent.com/55725505/65656593-bab02180-e063-11e9-9338-e6e45bdecf29.png">
<img width="750" alt="Screen Shot 2019-09-26 at 1 44 22 pm" src="https://user-images.githubusercontent.com/55725505/65656686-17abd780-e064-11e9-9e1a-65c600ac1f8d.png">

**Comment by markendley** [comment]
done. For now on when you add 3 images, choose the new "center" radio button
