### ISSUE TITLE
Large white space

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#41]
This doesnt appear to be fixed?

<img width="969" alt="Screen Shot 2019-12-03 at 9 36 37 am" src="https://user-images.githubusercontent.com/55725505/70001152-a97a1880-15b0-11ea-8f66-3ba20fca1921.png">
<img width="1268" alt="Screen Shot 2019-12-03 at 9 37 23 am" src="https://user-images.githubusercontent.com/55725505/70001159-ada63600-15b0-11ea-957b-2abd1660e066.png">

**Comment by markendley** [comment]
For now on when you edit those video galleries, you'll see a new field called "Orientation", so if you've got square videos, select the Square one.

Then you'll get this

http://marke2.sg-host.com/plumpspry/case-study/pacificepping/

**Comment by markendley** [comment]
also reduced the space before and after

**Comment by LaraStudioFriday** [comment]
Can you send me a screen shot of what youre seeing?

I can still see this...
<img width="1272" alt="Screen Shot 2019-12-04 at 10 08 33 am" src="https://user-images.githubusercontent.com/55725505/70097700-13acbf00-167e-11ea-8526-f340fec47350.png">

**Comment by markendley** [comment]
When I go to this page http://marke2.sg-host.com/plumpspry/case-study/pacificepping/, this is what I see....

![Screen Shot 2019-12-04 at 11 04 01 am](https://user-images.githubusercontent.com/6570606/70100430-cd5b5e00-1685-11ea-82c6-96ff1fde9a87.png)
