### ISSUE TITLE
Connor on a phone

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#42]
Should these images be the same size?

![78329029_1549819321823391_5438460995204808704_n](https://user-images.githubusercontent.com/55725505/70194798-da488200-1757-11ea-874e-a05fbfc23ac0.jpg)
![78847995_564674897659924_7677508849124769792_n](https://user-images.githubusercontent.com/55725505/70194799-dae11880-1757-11ea-938f-7e9bf4b5f7dc.jpg)

**Comment by markendley** [comment]
Just made a small fix to the code but we still need mobile version images.

Please go here, and then upload portrait versions.

http://marke2.sg-host.com/plumpspry/wp-admin/post.php?post=549&action=edit


![Screen Shot 2019-12-09 at 2 37 47 pm](https://user-images.githubusercontent.com/6570606/70405502-81e3ee00-1a91-11ea-8d40-fa0277518333.png)

**Comment by markendley** [comment]
620 x 780 pixels
