### ISSUE TITLE
Everything has increased in size. 

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#43]
![Screen Shot 2019-12-09 at 1 19 21 pm](https://user-images.githubusercontent.com/55725505/70403910-632f2880-1a8c-11ea-841c-619a2672b2f4.png)

This image is from Paul - he was happy for the body copy to increase in font size - but no has everything else - headings, titles etc.

**Comment by markendley** [comment]
OK I reverted it back to how it was before, and then I increased the body copy again.
