### ISSUE TITLE
3-4 horizontal images in a row

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#44]
<img width="1470" alt="Screen Shot 2019-12-09 at 1 13 50 pm" src="https://user-images.githubusercontent.com/55725505/70404168-4e06c980-1a8d-11ea-99a5-e215e57bd2d3.png">

<img width="882" alt="Screen Shot 2019-12-09 at 1 52 46 pm" src="https://user-images.githubusercontent.com/55725505/70404215-6c6cc500-1a8d-11ea-9bae-d6d809b482ec.png">

As per chat

**Comment by LaraStudioFriday** [comment]
Paul prefers this layout please for larger screens - Jake mocked this up for Paul btw
![Screen Shot 2019-12-09 at 3 59 07 pm (1)](https://user-images.githubusercontent.com/55725505/70409397-bc548780-1a9f-11ea-9ea7-5b1f7d17ef9c.png)

**Comment by markendley** [comment]
ok, check it out!

http://marke2.sg-host.com/plumpspry/case-study/connor-retail-strategy/

**Comment by LaraStudioFriday** [comment]
ok cool - how do i remove the landscape image at the top?

<img width="1253" alt="Screen Shot 2019-12-10 at 9 29 38 am" src="https://user-images.githubusercontent.com/55725505/70478662-a7273980-1b2f-11ea-9991-c9033187d9d3.png">

I tried removing the landscape shots here:
<img width="771" alt="Screen Shot 2019-12-10 at 9 24 40 am" src="https://user-images.githubusercontent.com/55725505/70478681-b4442880-1b2f-11ea-892b-f32b48cd5a70.png">

**Comment by markendley** [comment]
That's a different row.

**Comment by markendley** [comment]
A different slider

**Comment by LaraStudioFriday** [comment]
so which slider should I delete?

**Comment by markendley** [comment]
it was just the one above, I just deleted it for ya
