### ISSUE TITLE
Safari and chrome

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#45]
It is also different sizes on different browsers. 

Paul sent me this image:

![IMG_2079](https://user-images.githubusercontent.com/55725505/70404631-d33eae00-1a8e-11ea-804e-b0135242d90c.jpeg)

Overall he said the text is MASSIVE everywhere.

**Comment by markendley** [comment]
When I view the website on Safari and Chrome they're very identical.

Can you check the settings on both laptops and browsers, there might be a difference in "default font size" this feature can override the font-size I've defined in my code.
