### ISSUE TITLE
OUR APPROACH PAGE

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#46]
THE IMAGE IS CROPPING - so you cant see their desk?

<img width="1277" alt="Screen Shot 2019-12-09 at 2 34 12 pm" src="https://user-images.githubusercontent.com/55725505/70405351-01bd8880-1a91-11ea-9ce5-672afd49e466.png">

should look more like this:
<img width="1251" alt="image002 (4)" src="https://user-images.githubusercontent.com/55725505/70406310-662e1700-1a94-11ea-8c1a-4eef921a0464.png">

**Comment by markendley** [comment]
whilst we're waiting for Paul, I created a new field

for now on, in order to have a top image banner, use this one

![Screen Shot 2019-12-09 at 3 23 42 pm](https://user-images.githubusercontent.com/6570606/70407335-06d20600-1a98-11ea-90cd-e7f23cc533f7.png)

**Comment by LaraStudioFriday** [comment]
ok Paul has said to shrink the image with white space  - see attachment. Doesn't  need to be full width. 
<img width="759" alt="Screen Shot 2019-12-09 at 3 06 40 pm" src="https://user-images.githubusercontent.com/55725505/70409480-ffaef600-1a9f-11ea-85ec-6f9f71a27005.png">

**Comment by markendley** [comment]
easy done
http://marke2.sg-host.com/plumpspry/our-approach/
