### ISSUE TITLE
Cropping of images

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#48]
http://marke2.sg-host.com/plumpspry/case-study/pacificepping/

How can we stop image cropping off top and bottom of magazine?

<img width="695" alt="Screen Shot 2019-12-11 at 9 24 12 am" src="https://user-images.githubusercontent.com/55725505/70574581-8bd43100-1bf8-11ea-9a03-992045b0bdb9.png">
<img width="1269" alt="Screen Shot 2019-12-11 at 9 27 45 am" src="https://user-images.githubusercontent.com/55725505/70574582-8bd43100-1bf8-11ea-8359-03754833bc5a.png">

**Comment by markendley** [comment]
I'll need to fix

**Comment by markendley** [comment]
it's fixed now

http://marke2.sg-host.com/plumpspry/case-study/pacificepping/

**Comment by markendley** [comment]
minor glitch in the code but you did the right thing

![ ](https://user-images.githubusercontent.com/6570606/70615160-fcfaff00-1c5f-11ea-8af3-96cd063d8bc6.png)

**Comment by LaraStudioFriday** [comment]
So I did contain on this page - but its still now showing full image?

http://marke2.sg-host.com/plumpspry/catalogues/

<img width="1258" alt="Screen Shot 2019-12-12 at 10 58 50 am" src="https://user-images.githubusercontent.com/55725505/70670883-82b59380-1cce-11ea-9f3e-02ef00eb73d7.png">
<img width="411" alt="Screen Shot 2019-12-12 at 10 57 21 am" src="https://user-images.githubusercontent.com/55725505/70670889-86e1b100-1cce-11ea-892e-167c985821d2.png">

**Comment by markendley** [comment]
Oh, that's a square image

This banners are only suitable for wide rectangle images

You gotta reupload a different version 2000 x 1000 pixels (or double for retina)
