### ISSUE TITLE
Please check spacing

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#50]
<img width="499" alt="Screen Shot 2019-12-12 at 12 17 44 pm" src="https://user-images.githubusercontent.com/55725505/70674221-76830380-1cd9-11ea-8195-2bd12d825278.png">
<img width="493" alt="Screen Shot 2019-12-12 at 12 17 49 pm" src="https://user-images.githubusercontent.com/55725505/70674225-7a168a80-1cd9-11ea-851e-da2e97738aa5.png">

http://marke2.sg-host.com/plumpspry/catalogues/
http://marke2.sg-host.com/plumpspry/creative/

**Comment by markendley** [comment]
Fixed

For the those top images we're using the "page banner" field now
