### ISSUE TITLE
Animations not working on an i phone

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#53]
Think this is an i phone issue? 

They play on android. 

See this page - http://marke2.sg-host.com/plumpspry/social-media/

The presents in the header animation are not moving on my i-phone. 

Also, this page http://marke2.sg-host.com/plumpspry/case-study/pacificepping/

The animation are not working on my i-phone

**Comment by markendley** [comment]
Animated gifs will work, but not videos.

This is because video autoplay doesn't work on phones.
