### ISSUE TITLE
Spacing of heading on social media page

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#54]
Not consistent
<img width="512" alt="Screen Shot 2019-12-13 at 3 29 56 pm" src="https://user-images.githubusercontent.com/55725505/70769897-63e2fa00-1dbf-11ea-9a73-62d933c36565.png">
<img width="865" alt="Screen Shot 2019-12-13 at 3 30 02 pm" src="https://user-images.githubusercontent.com/55725505/70769898-63e2fa00-1dbf-11ea-9ea3-9e2c3cf6c2da.png">
<img width="879" alt="Screen Shot 2019-12-13 at 3 30 07 pm" src="https://user-images.githubusercontent.com/55725505/70769900-647b9080-1dbf-11ea-8562-28c3883e5979.png">

See issue #52

**Comment by markendley** [comment]
Is that better now?
