### ISSUE TITLE
Qeustion

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#55]
When you use the emulator for screen size - is this just based on the size of the screen? For example can this test iphone versus android? We seem to be having issues with both devices showing differently.eg mp4 playing on an android but not iphone. How do we screen share a mobile phone with Paul? Use the emulator?

**Comment by markendley** [comment]
The emulator is only accurate for something that a web developer will find useful. But not in this case

**Comment by LaraStudioFriday** [comment]
Sorry - so how do you test on android and iphone??

**Comment by markendley** [comment]
You mean how do I test?

1. Google Chrome Emulator
2. Safari emulator
3. My own Android
4. My own iPad

iPhone?
I use the emulator to check how things resized and laided out and I use the iPad to see how iOS picks and handles events.
