### ISSUE TITLE
On a phone request a call back/Contact page

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#56]
When we put a number into the phone field to test it - we got this message. 

![Screen Shot 2019-12-16 at 9 55 19 am](https://user-images.githubusercontent.com/55725505/70871302-04b8fb80-1ff2-11ea-8421-a57ffd7b9c40.png)

The user doesn't input an email address, so this message should read 'Thanks, we'll be in touch shortly'.

Mark, is there a way for the user to get a confirmation text? Or is this going to be too complicated?

**Comment by markendley** [comment]
message done

Send an sms? Too complicated we'll need an API
