### ISSUE TITLE
Case study - http://marke2.sg-host.com/plumpspry/case-study/brand-communication-canberra-centre/

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#59]
on desktop the images are cropped

<img width="1414" alt="Screen Shot 2019-12-16 at 10 23 41 am" src="https://user-images.githubusercontent.com/55725505/70871644-6b8be400-1ff5-11ea-86b3-209789bcd79a.png">

<img width="1385" alt="Screen Shot 2019-12-16 at 10 24 02 am" src="https://user-images.githubusercontent.com/55725505/70871685-d6d5b600-1ff5-11ea-8b7a-3b94429c23cb.png">

**Comment by markendley** [comment]
fixed
