### ISSUE TITLE
Case study - http://marke2.sg-host.com/plumpspry/case-study/brand-communication-canberra-centre/

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#60]
on an i-phone the video placeholder images are not visible? 

![79827089_2778455525540341_6280513295208153088_n](https://user-images.githubusercontent.com/55725505/70871723-27e5aa00-1ff6-11ea-9d03-3fc8cdbd26cf.jpg)

**Comment by markendley** [comment]
you didn't put any place holders

**Comment by markendley** [comment]
fixed
