### ISSUE TITLE
Pacific epping case study

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#61]
Images are now left aligned on a desktop

<img width="1018" alt="Screen Shot 2019-12-16 at 10 29 53 am" src="https://user-images.githubusercontent.com/55725505/70871755-7d21bb80-1ff6-11ea-9742-abfbc853801b.png">

<img width="1342" alt="Screen Shot 2019-12-16 at 10 28 44 am" src="https://user-images.githubusercontent.com/55725505/70871761-8b6fd780-1ff6-11ea-9f36-48057898e364.png">

Could these actually be the same height as the find seek pay image underneath?

<img width="1177" alt="Screen Shot 2019-12-16 at 11 25 33 am" src="https://user-images.githubusercontent.com/55725505/70871788-ce31af80-1ff6-11ea-8a6c-502630953c48.png">

Paul was happy to see these as individual shots - so maybe centre them too.

**Comment by markendley** [comment]
did you fix these?
