### ISSUE TITLE
font size of body copy can be reduced slightly. It’s too big now.

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#66]

**Comment by markendley** [comment]
This is one of the things that we need to dicuss with Paul, I've done this too many times now.

**Comment by LaraStudioFriday** [comment]
ok - he wanted the body copy to match this - https://www.smh.com.au/

<img width="286" alt="Screen Shot 2020-01-08 at 4 13 22 pm" src="https://user-images.githubusercontent.com/55725505/71952186-ea112580-3231-11ea-9ba4-06a02f3f6832.png">

**Comment by markendley** [comment]
Oh, this old, I already fixed this.

During the meeting, I went ahead and made the font change, and then showed him. he approved!
