### ISSUE TITLE
Replace with animated gifs

### ISSUE THREAD

**Issue by markendley** [markendley/plmpndspry#68]
http://marke2.sg-host.com/plumpspry/case-study/pacificepping/

Change these from videos to Animated gifs so they will play on mobile.

![Screen Shot 2019-12-22 at 8 17 36 pm](https://user-images.githubusercontent.com/6570606/71319878-25a0b580-24f8-11ea-9f98-ba147b38e996.png)

**Comment by LaraStudioFriday** [comment]
Waiting on smaller file sizes from Paul's team
