### ISSUE TITLE
2 images

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#7]
Is there a way we can make 2 images next to each other a bit smaller. 

<img width="754" alt="Screen Shot 2019-10-11 at 1 18 01 pm" src="https://user-images.githubusercontent.com/55725505/66619822-064cf880-ec2a-11e9-9b74-9912faf475e4.png">

Paul likes this, and at the moment they are coming up like this:

<img width="1247" alt="Screen Shot 2019-10-11 at 1 22 03 pm" src="https://user-images.githubusercontent.com/55725505/66619868-30061f80-ec2a-11e9-8e2a-d2f5ebb3b446.png">

**Comment by markendley** [comment]
done
