### ISSUE TITLE
New wordpress logon details

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#70]
Username - plumpandspry
Password - %9rJ9GR{d$PZ

**Comment by markendley** [comment]
The logins didn't work for me

and I already have my own.

**Comment by LaraStudioFriday** [comment]
I bought the domain through

crazydomains.com.au

hosted through there too I believe.

 

Below is login and password.

<img width="527" alt="image001 (4)" src="https://user-images.githubusercontent.com/55725505/72025264-ac60db00-32cb-11ea-90ff-5a674e4cb52b.png">

**Comment by markendley** [comment]
Done

When paul logins to 
https://www.plumpandspry.com.au/wp-admin

he can use

Username - plumpandspry
Password - %9rJ9GR{d$PZ
