### ISSUE TITLE
Re-order

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#72]
Jake needs to mock up the re-order of the catalogue pages on this page - http://marke2.sg-host.com/plumpspry/case-study/digital-content-robina-town-centre/

**Comment by markendley** [comment]
I think we spoke about this at the meeting
and I fixed the order

Now the order is....
1. Cover
2. single on top, spread on bottom
3. spread, spread
4. spread on top, single on bottom

Did someone change the settings? I also changed the size of each of these four pictures so there's less white space around


![Screen Shot 2020-01-08 at 8 11 19 pm](https://user-images.githubusercontent.com/6570606/71965078-112c1f00-3253-11ea-8047-c664efbabb1f.png)

**Comment by LaraStudioFriday** [comment]
Hey Mark, 

The images still look a bit small on my laptop?  Can you please re-look at this.
<img width="1273" alt="Screen Shot 2020-01-09 at 7 42 15 pm" src="https://user-images.githubusercontent.com/55725505/72051961-55352780-3318-11ea-9783-9eac8b73f93d.png">
