### ISSUE TITLE
QVB

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#75]
From Paul - This red tile does not animate on mobile view:

Mark - it did before ? What is going on? 
![82100379_488454105398049_6121757323829444608_n](https://user-images.githubusercontent.com/55725505/72230808-02a38600-360c-11ea-92b4-818408999653.jpg)

**Comment by markendley** [comment]
Hey LAra,

Remember how I said that movie autoplay doesn't work on phones.

Luckily I found a solution to that, I just updated the code, does autoplay work now?
