### ISSUE TITLE
Canberra case study

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#76]
From Paul - http://marke2.sg-host.com/plumpspry/case-study/brand-communication-canberra-centre/

we spoke about closing up the gaps between mags, but this is STILL REALLY gappy.

Can you please fix.
![image005 (1)](https://user-images.githubusercontent.com/55725505/72231028-1a2f3e80-360d-11ea-9df5-4bd8228b0e4f.png)

**Comment by markendley** [comment]
fixed
