### ISSUE TITLE
IGA case study

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#78]
From Paul - http://marke2.sg-host.com/plumpspry/case-study/iga/

can we make this auto play?

Please make video bigger. Looks tiny on mobile.

On desktop version theres too much space above and below it.

![image007 (3)](https://user-images.githubusercontent.com/55725505/72231523-0df8b080-3610-11ea-94a5-6a328d6f80db.png)

**Comment by markendley** [comment]
No, Vimeo autoplay isn't supported on phones. I have no control over that.

- the way around it would be to replace it with an animated gif
- if that last test worked for QVB #75 , then another way around this would be to make it an mp4 upload

**Comment by LaraStudioFriday** [comment]
Yes it now autoplays - but the video still looks small on a phone. 

![83718897_2410535512594383_3863150008454873088_n](https://user-images.githubusercontent.com/55725505/72395698-7077bb00-378e-11ea-9828-c945d1426a6f.jpg)

**Comment by markendley** [comment]
fixed

**Comment by LaraStudioFriday** [comment]
It still looks small on my phone?
