### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#79]
From Paul - Forms: Please check all emails / phone boxes are working.

Ie on this page:

http://marke2.sg-host.com/plumpspry/contact/

I filled out email box, but no email received…

**Comment by markendley** [comment]
Oh, they won't work on the staging server.
The form submissions are also saved in the WP admin so we can assure you that you won't miss out of any leads even though you don't recieve the notification email.

On that note I've checked your domain and I can see that you're emails are with Outlook. We'll need access to your outlook account as well.

You see these days emails can get tricky to work, mailboxes and mailservers are becoming more and more sensitive and protective to spam, malicious mail and fraud senders and so to ensure that you will receive email notifications from the site, we need full access to it all so we can make sure all the right settings are in place.

We're not gonna lie to you, we've had problems with outlook before. But don't worry, form submissions are saved and once we get access to everything it'll be alright.

Worst case: we'll need you to sign up with Mailgun which is practically free.
