### ISSUE TITLE
Can we hard return the homepage title to look like this on a phone?

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#8]
<img width="321" alt="Screen Shot 2019-10-14 at 10 06 09 am" src="https://user-images.githubusercontent.com/55725505/66723871-4f8b8b00-ee6a-11e9-9214-9a6f18c95f94.png">

**Comment by markendley** [comment]
Done.

(I created a new field called "Alternative page title", this field allows you to have breaks)
