### ISSUE TITLE
Contact/Homepage

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#82]
<img width="649" alt="Screen Shot 2020-01-14 at 1 10 30 pm" src="https://user-images.githubusercontent.com/55725505/72307709-50cd8d80-36cf-11ea-9e56-eb2537077e86.png">

I have updated the copy as per Paul's instruction - http://marke2.sg-host.com/plumpspry/wp-admin/admin.php?page=site-wide

BUT the change isn't showing on the phone?

ALSO, on the contact page on a desktop can you please reduce the spacing between:

Interested? We’d love to hear from you.

T: +61 2 9690 1109

.....so that it matches the spacing as seen on the homepage:

<img width="541" alt="Screen Shot 2020-01-14 at 1 21 02 pm" src="https://user-images.githubusercontent.com/55725505/72308502-c1c17500-36d0-11ea-922e-ce68e7f58ec5.png">

**Comment by markendley** [comment]
please check again, I turned off that caching plugin

**Comment by LaraStudioFriday** [comment]
Ok just on a phone the spacing between -  

Interested? We’d love to hear from you.

T: +61 2 9690 1109

Still looks a bit gappy
![82187801_720712695340852_7435284298632003584_n](https://user-images.githubusercontent.com/55725505/72394140-4cfe4180-3789-11ea-8728-8ca59eeb731a.jpg)

**Comment by markendley** [comment]
cache cleared?

**Comment by markendley** [comment]
I just checked, theere's no weirld gapping, but I fixed the orphan.
