### ISSUE TITLE
Homepage case study text

### ISSUE THREAD

**Issue by LaraStudioFriday** [markendley/plmpndspry#9]
For the full width case studies, can we please put the descriptor text into a column or have it run over a couple of lines-  maybe we can hard return? 

Just looks odd on a a laptop with a long line of text. 
<img width="1188" alt="Screen Shot 2019-10-14 at 10 19 58 am" src="https://user-images.githubusercontent.com/55725505/66724032-7054e000-ee6c-11e9-825f-2f54e4c3497b.png">

Really like this - 

<img width="650" alt="Screen Shot 2019-10-14 at 10 22 10 am" src="https://user-images.githubusercontent.com/55725505/66724036-7f3b9280-ee6c-11e9-82f2-b0ef2ef63b00.png">

**Comment by markendley** [comment]
done
